services:
  azurite-http:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    container_name: azurite-http
    ports:
      - "20000:10000"
    volumes:
      - ./data/azurite-http:/data
    command: azurite --blobHost 0.0.0.0 --location /data --debug /data/debug.log

  azurite-https:
    image: mcr.microsoft.com/azure-storage/azurite:3.35.0
    container_name: azurite-https
    ports:
      - "21000:10000"
    volumes:
      - ./data/azurite-https:/data
      - ./certs/server.pem:/certs/server.pem:ro
      - ./certs/server-key.pem:/certs/server-key.pem:ro
    command: azurite --blobHost 0.0.0.0 --location /data --cert /certs/server.pem --key /certs/server-key.pem --oauth basic --debug /data/debug.log